/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SPOLE1C_JNI */

#ifndef _Included_SPOLE1C_JNI
#define _Included_SPOLE1C_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SPOLE1C_JNI
 * Method:    nativeConnect
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_SPOLE1C_1JNI_nativeConnect
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     SPOLE1C_JNI
 * Method:    nativeCutAndPrint
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SPOLE1C_1JNI_nativeCutAndPrint
  (JNIEnv *, jobject);

/*
 * Class:     SPOLE1C_JNI
 * Method:    nativeGetShortECRStatus
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_SPOLE1C_1JNI_nativeGetShortECRStatus
  (JNIEnv *, jobject);

/*
 * Class:     SPOLE1C_JNI
 * Method:    nativeGetResultCode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SPOLE1C_1JNI_nativeGetResultCode
  (JNIEnv *, jobject);

/*
 * Class:     SPOLE1C_JNI
 * Method:    nativeGetEndOfPrinting
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SPOLE1C_1JNI_nativeGetEndOfPrinting
  (JNIEnv *, jobject);

/*
 * Class:     SPOLE1C_JNI
 * Method:    nativeGetKkmType
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_SPOLE1C_1JNI_nativeGetKkmType
  (JNIEnv *, jobject);

/*
 * Class:     SPOLE1C_JNI
 * Method:    nativeGetKkmVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_SPOLE1C_1JNI_nativeGetKkmVersion
  (JNIEnv *, jobject);

/*
 * Class:     SPOLE1C_JNI
 * Method:    nativeGetLastShiftInFiscalMemory
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_SPOLE1C_1JNI_nativeGetLastShiftInFiscalMemory
  (JNIEnv *, jobject);

/*
 * Class:     SPOLE1C_JNI
 * Method:    nativeBeep
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SPOLE1C_1JNI_nativeBeep
  (JNIEnv *, jobject);

/*
 * Class:     SPOLE1C_JNI
 * Method:    nativeSetDate
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_SPOLE1C_1JNI_nativeSetDate
  (JNIEnv *, jobject, jstring);

/*
 * Class:     SPOLE1C_JNI
 * Method:    nativeConfirmDate
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_SPOLE1C_1JNI_nativeConfirmDate
  (JNIEnv *, jobject, jstring);

/*
 * Class:     SPOLE1C_JNI
 * Method:    nativeSetTime
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_SPOLE1C_1JNI_nativeSetTime
  (JNIEnv *, jobject, jstring);

/*
 * Class:     SPOLE1C_JNI
 * Method:    nativePrintText
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_SPOLE1C_1JNI_nativePrintText
  (JNIEnv *, jobject, jstring);

/*
 * Class:     SPOLE1C_JNI
 * Method:    nativeBuy
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_SPOLE1C_1JNI_nativeBuy
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     SPOLE1C_JNI
 * Method:    nativeSale
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_SPOLE1C_1JNI_nativeSale
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     SPOLE1C_JNI
 * Method:    nativeReturnSale
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_SPOLE1C_1JNI_nativeReturnSale
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     SPOLE1C_JNI
 * Method:    nativeCheckSubTotal
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SPOLE1C_1JNI_nativeCheckSubTotal
  (JNIEnv *, jobject);

/*
 * Class:     SPOLE1C_JNI
 * Method:    nativeCloseCheck
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_SPOLE1C_1JNI_nativeCloseCheck
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     SPOLE1C_JNI
 * Method:    nativeCancelCheck
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SPOLE1C_1JNI_nativeCancelCheck
  (JNIEnv *, jobject);

/*
 * Class:     SPOLE1C_JNI
 * Method:    nativeXreport
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_SPOLE1C_1JNI_nativeXreport
  (JNIEnv *, jobject, jstring);

/*
 * Class:     SPOLE1C_JNI
 * Method:    nativeZreport
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_SPOLE1C_1JNI_nativeZreport
  (JNIEnv *, jobject, jstring);

/*
 * Class:     SPOLE1C_JNI
 * Method:    nativeJournalPrint
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_SPOLE1C_1JNI_nativeJournalPrint
  (JNIEnv *, jobject, jstring);

/*
 * Class:     SPOLE1C_JNI
 * Method:    nativeJournalRead
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_SPOLE1C_1JNI_nativeJournalRead
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     SPOLE1C_JNI
 * Method:    nativeGetJournalNumber
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SPOLE1C_1JNI_nativeGetJournalNumber
  (JNIEnv *, jobject);

/*
 * Class:     SPOLE1C_JNI
 * Method:    nativeGetJournalRecordCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SPOLE1C_1JNI_nativeGetJournalRecordCount
  (JNIEnv *, jobject);

/*
 * Class:     SPOLE1C_JNI
 * Method:    nativeGetJournalRecord
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_SPOLE1C_1JNI_nativeGetJournalRecord
  (JNIEnv *, jobject, jint);

/*
 * Class:     SPOLE1C_JNI
 * Method:    nativeGetJournalReceiptByIndex
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_SPOLE1C_1JNI_nativeGetJournalReceiptByIndex
  (JNIEnv *, jobject, jint);

/*
 * Class:     SPOLE1C_JNI
 * Method:    nativeGetJournalReceiptByNumber
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_SPOLE1C_1JNI_nativeGetJournalReceiptByNumber
  (JNIEnv *, jobject, jint);

/*
 * Class:     SPOLE1C_JNI
 * Method:    nativePrintEklzReportFullByDate
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_SPOLE1C_1JNI_nativePrintEklzReportFullByDate
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     SPOLE1C_JNI
 * Method:    nativePrintEklzReportShortByDate
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_SPOLE1C_1JNI_nativePrintEklzReportShortByDate
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     SPOLE1C_JNI
 * Method:    nativePrintEklzReportFullByShift
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_SPOLE1C_1JNI_nativePrintEklzReportFullByShift
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     SPOLE1C_JNI
 * Method:    nativePrintEklzReportShortByShift
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_SPOLE1C_1JNI_nativePrintEklzReportShortByShift
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     SPOLE1C_JNI
 * Method:    nativePrintEklzReportControlTape
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_SPOLE1C_1JNI_nativePrintEklzReportControlTape
  (JNIEnv *, jobject, jint);

/*
 * Class:     SPOLE1C_JNI
 * Method:    nativeClosePort
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SPOLE1C_1JNI_nativeClosePort
  (JNIEnv *, jobject);

/*
 * Class:     SPOLE1C_JNI
 * Method:    fiscal54Fz
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SPOLE1C_1JNI_fiscal54Fz
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
