/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SPOLE_JNI */

#ifndef _Included_SPOLE_JNI
#define _Included_SPOLE_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SPOLE_JNI
 * Method:    nativeConnect
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_SPOLE_1JNI_nativeConnect
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     SPOLE_JNI
 * Method:    nativeCutAndPrint
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SPOLE_1JNI_nativeCutAndPrint
  (JNIEnv *, jobject);

/*
 * Class:     SPOLE_JNI
 * Method:    nativeGetShortECRStatus
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_SPOLE_1JNI_nativeGetShortECRStatus
  (JNIEnv *, jobject);

/*
 * Class:     SPOLE_JNI
 * Method:    nativeGetResultCode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SPOLE_1JNI_nativeGetResultCode
  (JNIEnv *, jobject);

/*
 * Class:     SPOLE_JNI
 * Method:    nativeGetEndOfPrinting
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SPOLE_1JNI_nativeGetEndOfPrinting
  (JNIEnv *, jobject);

/*
 * Class:     SPOLE_JNI
 * Method:    nativeGetKkmType
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_SPOLE_1JNI_nativeGetKkmType
  (JNIEnv *, jobject);

/*
 * Class:     SPOLE_JNI
 * Method:    nativeGetKkmVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_SPOLE_1JNI_nativeGetKkmVersion
  (JNIEnv *, jobject);

/*
 * Class:     SPOLE_JNI
 * Method:    nativeGetSerialNumber
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_SPOLE_1JNI_nativeGetSerialNumber
  (JNIEnv *, jobject);

/*
 * Class:     SPOLE_JNI
 * Method:    nativeGetPrinterStatus
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SPOLE_1JNI_nativeGetPrinterStatus
  (JNIEnv *, jobject);

/*
 * Class:     SPOLE_JNI
 * Method:    nativeGetLastShiftInFiscalMemory
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_SPOLE_1JNI_nativeGetLastShiftInFiscalMemory
  (JNIEnv *, jobject);

/*
 * Class:     SPOLE_JNI
 * Method:    nativeInit
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_SPOLE_1JNI_nativeInit
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     SPOLE_JNI
 * Method:    nativeInstall
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_SPOLE_1JNI_nativeInstall
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     SPOLE_JNI
 * Method:    nativeInstallEx
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_SPOLE_1JNI_nativeInstallEx
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     SPOLE_JNI
 * Method:    nativeSetDate
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_SPOLE_1JNI_nativeSetDate
  (JNIEnv *, jobject, jstring);

/*
 * Class:     SPOLE_JNI
 * Method:    nativeConfirmDate
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_SPOLE_1JNI_nativeConfirmDate
  (JNIEnv *, jobject, jstring);

/*
 * Class:     SPOLE_JNI
 * Method:    nativeSetTime
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_SPOLE_1JNI_nativeSetTime
  (JNIEnv *, jobject, jstring);

/*
 * Class:     SPOLE_JNI
 * Method:    nativePrintText
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_SPOLE_1JNI_nativePrintText
  (JNIEnv *, jobject, jstring);

/*
 * Class:     SPOLE_JNI
 * Method:    nativeOpenReceipt
 * Signature: (IILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_SPOLE_1JNI_nativeOpenReceipt
  (JNIEnv *, jobject, jint, jint, jstring, jint);

/*
 * Class:     SPOLE_JNI
 * Method:    nativeBuy
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_SPOLE_1JNI_nativeBuy
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     SPOLE_JNI
 * Method:    nativeAddItem3
 * Signature: (Ljava/lang/String;Ljava/lang/String;DLjava/lang/String;IILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_SPOLE_1JNI_nativeAddItem3
  (JNIEnv *, jobject, jstring, jstring, jdouble, jstring, jint, jint, jstring);

/*
 * Class:     SPOLE_JNI
 * Method:    nativeReturnSale
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_SPOLE_1JNI_nativeReturnSale
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     SPOLE_JNI
 * Method:    nativeSubTotal
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_SPOLE_1JNI_nativeSubTotal
  (JNIEnv *, jobject);

/*
 * Class:     SPOLE_JNI
 * Method:    nativePayment
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_SPOLE_1JNI_nativePayment
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     SPOLE_JNI
 * Method:    nativeCloseReceipt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SPOLE_1JNI_nativeCloseReceipt
  (JNIEnv *, jobject);

/*
 * Class:     SPOLE_JNI
 * Method:    nativeCancelReceipt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SPOLE_1JNI_nativeCancelReceipt
  (JNIEnv *, jobject);

/*
 * Class:     SPOLE_JNI
 * Method:    nativeXreport
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_SPOLE_1JNI_nativeXreport
  (JNIEnv *, jobject, jstring);

/*
 * Class:     SPOLE_JNI
 * Method:    nativeZreport
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_SPOLE_1JNI_nativeZreport
  (JNIEnv *, jobject, jstring);

/*
 * Class:     SPOLE_JNI
 * Method:    nativeOpenStornoReceipt
 * Signature: (ILjava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_SPOLE_1JNI_nativeOpenStornoReceipt
  (JNIEnv *, jobject, jint, jstring, jint, jint);

/*
 * Class:     SPOLE_JNI
 * Method:    nativeAddStornoAmount
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_SPOLE_1JNI_nativeAddStornoAmount
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     SPOLE_JNI
 * Method:    nativeJournalPrint
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_SPOLE_1JNI_nativeJournalPrint
  (JNIEnv *, jobject, jstring);

/*
 * Class:     SPOLE_JNI
 * Method:    nativePrintJournal
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_SPOLE_1JNI_nativePrintJournal
  (JNIEnv *, jobject, jstring);

/*
 * Class:     SPOLE_JNI
 * Method:    nativeJournalRead
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_SPOLE_1JNI_nativeJournalRead
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     SPOLE_JNI
 * Method:    nativeGetJournalNumber
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SPOLE_1JNI_nativeGetJournalNumber
  (JNIEnv *, jobject);

/*
 * Class:     SPOLE_JNI
 * Method:    nativeGetJournalRecordCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SPOLE_1JNI_nativeGetJournalRecordCount
  (JNIEnv *, jobject);

/*
 * Class:     SPOLE_JNI
 * Method:    nativeGetJournalRecord
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_SPOLE_1JNI_nativeGetJournalRecord
  (JNIEnv *, jobject, jint);

/*
 * Class:     SPOLE_JNI
 * Method:    nativeGetJournalReceiptByIndex
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_SPOLE_1JNI_nativeGetJournalReceiptByIndex
  (JNIEnv *, jobject, jint);

/*
 * Class:     SPOLE_JNI
 * Method:    nativeGetJournalReceiptByNumber
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_SPOLE_1JNI_nativeGetJournalReceiptByNumber
  (JNIEnv *, jobject, jint);

/*
 * Class:     SPOLE_JNI
 * Method:    nativePrintEklzReportFullByDate
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_SPOLE_1JNI_nativePrintEklzReportFullByDate
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     SPOLE_JNI
 * Method:    nativePrintEklzReportShortByDate
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_SPOLE_1JNI_nativePrintEklzReportShortByDate
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     SPOLE_JNI
 * Method:    nativePrintEklzReportFullByShift
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_SPOLE_1JNI_nativePrintEklzReportFullByShift
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     SPOLE_JNI
 * Method:    nativePrintEklzReportShortByShift
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_SPOLE_1JNI_nativePrintEklzReportShortByShift
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     SPOLE_JNI
 * Method:    nativePrintEklzReportControlTape
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_SPOLE_1JNI_nativePrintEklzReportControlTape
  (JNIEnv *, jobject, jint);

/*
 * Class:     SPOLE_JNI
 * Method:    nativeZCopy
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_SPOLE_1JNI_nativeZCopy
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     SPOLE_JNI
 * Method:    nativeZCopyClear
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SPOLE_1JNI_nativeZCopyClear
  (JNIEnv *, jobject);

/*
 * Class:     SPOLE_JNI
 * Method:    nativeZCopyPrintRegistration
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SPOLE_1JNI_nativeZCopyPrintRegistration
  (JNIEnv *, jobject);

/*
 * Class:     SPOLE_JNI
 * Method:    nativeZCopyPrintAll
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SPOLE_1JNI_nativeZCopyPrintAll
  (JNIEnv *, jobject);

/*
 * Class:     SPOLE_JNI
 * Method:    nativeZCopyPrintByOrderNumber
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_SPOLE_1JNI_nativeZCopyPrintByOrderNumber
  (JNIEnv *, jobject, jint);

/*
 * Class:     SPOLE_JNI
 * Method:    nativeZCopyPrintByShiftNumber
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_SPOLE_1JNI_nativeZCopyPrintByShiftNumber
  (JNIEnv *, jobject, jint);

/*
 * Class:     SPOLE_JNI
 * Method:    nativeClosePort
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SPOLE_1JNI_nativeClosePort
  (JNIEnv *, jobject);

/*
 * Class:     SPOLE_JNI
 * Method:    fiscal54Fz
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SPOLE_1JNI_fiscal54Fz
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
